# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # http://christianki.github.io
url: "" # http://christianki.github.io

twitter_username:
github_username:

# Build settings
markdown: kramdown
